#
# This file was generated from the asynchronous client at conftest.py by generate_synchronous_client.sh
# Do not edit this file directly, instead edit the original file and regenerate this file.
#


import pytest

from invenio_nrp.client import SyncClient


@pytest.fixture()
def local_client(nrp_repository_config):
    ret = SyncClient(alias="local", config=nrp_repository_config)
    ret.info()
    return ret


@pytest.fixture()
def zenodo_client(nrp_repository_config):
    ret = SyncClient(alias="zenodo", config=nrp_repository_config)
    ret.info()
    return ret


@pytest.fixture(scope="function")
def local_records(local_client):
    return local_client.user_records()


@pytest.fixture(scope="function")
def draft_record(request, local_client):
    records_client = local_client.user_records
    return records_client().create_record(
        {
            "metadata": {"title": f"async draft record for {request.node.name}"},
            "files": {"enabled": False},
        },
        community="acom",
        files_enabled=False,
    )


@pytest.fixture(scope="function")
def draft_record_with_files(request, local_client):
    records_client = local_client.user_records
    return records_client().create_record(
        {
            "metadata": {"title": f"async draft record for {request.node.name}"},
        },
        community="acom",
        files_enabled=True,
    )

