#
# This file was generated from the asynchronous client at test_async_file_structuring.py by generate_synchronous_client.sh
# Do not edit this file directly, instead edit the original file and regenerate this file.
#


from invenio_nrp.client.sync_client.files.files import File, FileLinks
from invenio_nrp.types.converter import converter


def test_file_structuring():
    data = {
        "key": "blah.txt",
        "links": {
            "self": "http://localhost:5000/api/files/1",
            "content": "http://localhost:5000/api/files/1/content",
        }
    }
    output = converter.structure(data, File)
