#
# This file was generated from the asynchronous client at test_async_record_list.py by generate_synchronous_client.sh
# Do not edit this file directly, instead edit the original file and regenerate this file.
#


from invenio_nrp.client.sync_client.records import RecordList
from invenio_nrp.types.converter import converter


def test_record_list():
    data = {
        "hits": {
            "total": 100,
            "hits": [
                {
                    "metadata": {"title": "test1"},
                    "links": {"self": "http://localhost:5000/api/records/1"},
                    "created": "2021-01-01T00:00:00Z",
                    "updated": "2021-01-01T00:00:00Z",
                    "id": "1",
                },
            ],
        },
        "aggregations": {},
        "links": {
            "self": "http://localhost:5000/api/records",
        },
    }
    output = converter.structure(data, RecordList)
