#
# This file was generated from the asynchronous client at test_async_files.py by generate_synchronous_client.sh
# Do not edit this file directly, instead edit the original file and regenerate this file.
#


from invenio_nrp.client.sync_client.files import File
from invenio_nrp.client.sync_client.files.source.memory import MemoryDataSource
from invenio_nrp.client.sync_client.records import Record
from invenio_nrp.client.sync_client.request_types import RequestType
from invenio_nrp.client.sync_client.requests import Request


def test_list_files(draft_record: Record, draft_record_with_files: Record):
    files = draft_record.files()
    listing = files.list()
    assert listing.enabled == False
    assert listing.entries == []
    assert listing.links.self_ is not None

    files = draft_record_with_files.files()
    listing = files.list()
    assert listing.enabled == True
    assert listing.entries == []

    data = b"Hello world!"
    committed_upload = files.upload(
        key="blah.txt",
        metadata={"title": "blah"},
        file=MemoryDataSource(data, content_type="text/plain"),
    )

    print(committed_upload)
    assert committed_upload.links.content is not None
    assert committed_upload.status == "completed"
    assert committed_upload.metadata["title"] == "blah"
    assert committed_upload.size == len(data)
    assert committed_upload.checksum is not None

    listing = files.list()
    assert listing.enabled == True
    assert len(listing.entries) == 1
    assert listing.entries[0].key == "blah.txt"
