#
# This file was generated from the asynchronous client at files/sink/__init__.py by generate_synchronous_client.sh
# Do not edit this file directly, instead edit the original file and regenerate this file.
#


"""A base class and file and memory implementation for file downloads."""
