#
# This file was generated from the asynchronous client at info.py by generate_synchronous_client.sh
# Do not edit this file directly, instead edit the original file and regenerate this file.
#


"""Client for the .well-known/repository endpoint."""

from ...config import RepositoryConfig
from ...config.info import ModelInfo, RepositoryInfo
from ..errors import RepositoryClientError, RepositoryCommunicationError
from ..rdm import make_rdm_info
from .connection import Connection


class SyncInfoClient:
    """Client accessing the .well-known/repository endpoint."""

    def __init__(
        self,
        repository_config: RepositoryConfig,
        connection: Connection,
    ):
        """Initialize the client."""
        self._repository_config = repository_config
        self._connection = connection

    def info(self, refresh: bool = False) -> RepositoryInfo:
        """Retrieve info endpoint from the repository.

        :return: The parsed content of the info endpoint

        Note: as the endpoint info rarely changes (only when a new implementation
        is deployed), it is cached in the config object.

        Pass refresh=True to force a refresh and save the config (via client.config.save())
        afterwards.
        """
        if self._repository_config.info and not refresh:
            return self._repository_config.info

        try:
            info = self._connection.get(
                url=self._repository_config.well_known_repository_url,
                result_class=RepositoryInfo,
            )
            self._repository_config.info = info

            if not self._repository_config.info.links.models:
                raise ValueError("The repository does not provide the models link.")
            models = self._connection.get(
                url=self._repository_config.info.links.models,
                result_class=list[ModelInfo],
            )
            self._repository_config.info.models = {
                model.name: model for model in models
            }

        except* (RepositoryClientError, RepositoryCommunicationError):
            # not a NRP based repository, suppose that it is plain invenio rdm
            self._repository_config.info = make_rdm_info(self._repository_config.url)

        return self._repository_config.info

