#
# This file was generated from the asynchronous client at files/source/__init__.py by generate_synchronous_client.sh
# Do not edit this file directly, instead edit the original file and regenerate this file.
#


"""A source of data to upload to the repository."""

from .base import DataSource
from .file import FileDataSource
from .memory import MemoryDataSource

__all__ = ["DataSource", "FileDataSource", "MemoryDataSource"]
