#
# This file was generated from the asynchronous client at files/source/memory.py by generate_synchronous_client.sh
# Do not edit this file directly, instead edit the original file and regenerate this file.
#


"""Memory-based data source."""

import contextlib
from typing import Iterator

from ..os import DataReader
from .base import DataSource
from .memory_reader import MemoryReader


class MemoryDataSource(DataSource):
    """A data source that reads data from memory."""

    has_range_support = True

    def __init__(self, data: bytes, content_type: str):
        """Initialize the data source.

        :param data:                the data to be read
        :param content_type:        the content type of the data
        """
        self._data = data
        self._content_type = content_type

    # TODO: how to correctly type this?
    @contextlib.contextmanager
    def open(self, offset: int = 0) -> Iterator[DataReader]:  # type: ignore
        """Open the data source for reading."""
        yield MemoryReader(self._data[offset:])  # noqa ignore type

    def size(self) -> int:
        """Return the size of the data."""
        return len(self._data)

    def content_type(self) -> str:
        """Return the content type of the data."""
        return self._content_type

    def close(self) -> None:
        """Close the data source."""
        pass
