#
# Copyright (C) 2024 CESNET z.s.p.o.
#
# invenio-nrp is free software; you can redistribute it and/or
# modify it under the terms of the MIT License; see LICENSE file for more
# details.
#

#
# This file was generated from the asynchronous client at files/source/stdin.py by generate_synchronous_client.sh
# Do not edit this file directly, instead edit the original file and regenerate this file.
#


"""Data source that reads data from standard input."""

import contextlib
from pathlib import Path
from typing import Iterator

from ..os import DataReader, open_file
from .base import DataSource


class StdInDataSource(DataSource):
    """A data source that reads data from standard input."""

    has_range_support = False

    # TODO: how to correctly type this?
    @contextlib.contextmanager
    def open(self, offset: int = 0) -> Iterator[DataReader]:  # type: ignore
        """Open the data source for reading."""
        ret = open_file(Path("/sys/stdin"), mode="rb")
        yield ret
        ret.close()

    def size(self) -> int:
        """Return the size of the data - in this case -1 as unknown."""
        return -1

    def content_type(self) -> str:
        """Return the content type of the data."""
        return "application/octet-stream"

    def close(self) -> None:
        """Close the data source."""
        pass
