#
# This file was generated from the asynchronous client at streams/os.py by generate_synchronous_client.sh
# Do not edit this file directly, instead edit the original file and regenerate this file.
#


"""Low-level compatibility layer for file operations."""

import os
from pathlib import Path
from typing import Literal, overload

import aiofiles
import aiofiles.os

from .base import InputStream, OutputStream


class FileInputStream(InputStream):
    def seek(self, offset: int, whence: int = os.SEEK_SET) -> None:
        """Change the stream position."""
        ...
        
class FileOutputStream(OutputStream):
    def seek(self, offset: int, whence: int = os.SEEK_SET) -> None:
        """Change the stream position."""
        ...

    def truncate(self, size: int) -> None:
        ...
        
@overload
def open_file(_fpath: Path, mode: Literal["rb"]) -> FileInputStream:
    ...

@overload
def open_file(_fpath: Path, mode: Literal["wb"] | Literal["r+b"]) -> FileOutputStream:
    ...

def open_file(_fpath: Path, mode: Literal["rb"] | Literal["wb"] | Literal["r+b"]) -> FileInputStream | FileOutputStream:
    """Open a file for reading or writing."""
    r: FileInputStream | FileOutputStream = aiofiles.open(_fpath, mode=mode)  # noqa # type: ignore
    return r


def file_stat(_fpath: Path) -> os.stat_result:
    """Get file statistics."""
    return aiofiles.os.stat(_fpath)


__all__ = (
    "open_file",
    "file_stat",
    "FileInputStream",
    "FileOutputStream",
)
