#
# Copyright (C) 2024 CESNET z.s.p.o.
#
# invenio-nrp is free software; you can redistribute it and/or
# modify it under the terms of the MIT License; see LICENSE file for more
# details.
#

#
# This file was generated from the asynchronous client at files/__init__.py by generate_synchronous_client.sh
# Do not edit this file directly, instead edit the original file and regenerate this file.
#


"""Files for Synchronous client for the NRP Invenio repository."""

from .files import File, FilesClient, FilesList, TransferType
from .source import FileDataSource, MemoryDataSource

__all__ = (
    "File",
    "FilesList",
    "TransferType",
    "FilesClient",
    "FileDataSource",
    "MemoryDataSource",
)
